name: Python File Writter CI

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install pytest
    - name: Run tests
      run: python test_file_writer.py
    - name: Notify Success Via Email
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ganitniduniyanikunj10@gmail.com
        password: jqbz kvfy bwpw pxdi
        subject: "CI Build Success - ${{ github.repository }}"
        body: |
          The Build For ${{ github.repository }} on branch ${{ github.ref_name }} succeded.
          Commit: ${{ github.sha }}
        to: ganitniduniyanikunj10@gmail.com
        from: ganitniduniyanikunj10@gmail.com

